// Mocks generated by Mockito 5.4.6 from annotations
// in moustra/test/widgets/attachment/attachment_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:moustra/services/clients/attachment_api.dart' as _i3;
import 'package:moustra/services/dtos/attachment_dto.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAttachmentDto_0 extends _i1.SmartFake implements _i2.AttachmentDto {
  _FakeAttachmentDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AttachmentApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttachmentApi extends _i1.Mock implements _i3.AttachmentApi {
  MockAttachmentApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.AttachmentDto>> getAnimalAttachments(
    String? animalUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAnimalAttachments, [animalUuid]),
            returnValue: _i4.Future<List<_i2.AttachmentDto>>.value(
              <_i2.AttachmentDto>[],
            ),
          )
          as _i4.Future<List<_i2.AttachmentDto>>);

  @override
  _i4.Future<_i2.AttachmentDto> uploadAnimalAttachment(
    String? animalUuid,
    _i5.File? file, {
    String? attachmentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadAnimalAttachment,
              [animalUuid, file],
              {#attachmentType: attachmentType},
            ),
            returnValue: _i4.Future<_i2.AttachmentDto>.value(
              _FakeAttachmentDto_0(
                this,
                Invocation.method(
                  #uploadAnimalAttachment,
                  [animalUuid, file],
                  {#attachmentType: attachmentType},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.AttachmentDto>);

  @override
  _i4.Future<void> deleteAnimalAttachment(
    String? animalUuid,
    String? attachmentUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAnimalAttachment, [
              animalUuid,
              attachmentUuid,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getAttachmentLink(
    String? animalUuid,
    String? attachmentUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentLink, [animalUuid, attachmentUuid]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getAttachmentLink, [
                  animalUuid,
                  attachmentUuid,
                ]),
              ),
            ),
          )
          as _i4.Future<String>);
}
