// Mocks generated by Mockito 5.4.6 from annotations
// in moustra/test/services/clients/cage_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:moustra/services/clients/dio_api_client.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DioApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioApiClient extends _i1.Mock implements _i3.DioApiClient {
  MockDioApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i4.Future<_i2.Response<dynamic>> get(
    String? path, {
    Map<String, String>? query,
    bool? withoutAccountPrefix = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#query: query, #withoutAccountPrefix: withoutAccountPrefix},
            ),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#query: query, #withoutAccountPrefix: withoutAccountPrefix},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getWithQueryString(
    String? path, {
    required String? queryString,
    bool? withoutAccountPrefix = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getWithQueryString,
              [path],
              {
                #queryString: queryString,
                #withoutAccountPrefix: withoutAccountPrefix,
              },
            ),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(
                  #getWithQueryString,
                  [path],
                  {
                    #queryString: queryString,
                    #withoutAccountPrefix: withoutAccountPrefix,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> post(
    String? path, {
    Object? body,
    Map<String, String>? query,
    bool? withoutAccountPrefix = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #body: body,
                #query: query,
                #withoutAccountPrefix: withoutAccountPrefix,
              },
            ),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #body: body,
                    #query: query,
                    #withoutAccountPrefix: withoutAccountPrefix,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> postWithoutAuth(
    String? path, {
    Object? body,
    bool? withoutAccountPrefix = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postWithoutAuth,
              [path],
              {#body: body, #withoutAccountPrefix: withoutAccountPrefix},
            ),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(
                  #postWithoutAuth,
                  [path],
                  {#body: body, #withoutAccountPrefix: withoutAccountPrefix},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> put(
    String? path, {
    Object? body,
    Map<String, String>? query,
    Duration? receiveTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path], {#body: body, #query: query, #receiveTimeout: receiveTimeout}),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#put, [path], {#body: body, #query: query, #receiveTimeout: receiveTimeout}),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> patch(
    String? path, {
    Object? body,
    Map<String, String>? query,
    Duration? receiveTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#patch, [path], {#body: body, #query: query, #receiveTimeout: receiveTimeout}),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#patch, [path], {#body: body, #query: query, #receiveTimeout: receiveTimeout}),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> delete(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path]),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#delete, [path]),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> uploadFile(
    String? path, {
    required _i5.File? file,
    String? fileFieldName = 'file',
    Map<String, String>? fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [path],
              {#file: file, #fileFieldName: fileFieldName, #fields: fields},
            ),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(
                  #uploadFile,
                  [path],
                  {#file: file, #fileFieldName: fileFieldName, #fields: fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);
}
